#!/bin/bash

#creating sample file to print output to extract relevant data
rm -f sample.txt
touch sample.txt
grep 'density:' *.data > sample.txt
NLINE=$(wc -l < sample.txt)
echo $NLINE
density=$(awk 'FNR=='${NLINE}' { print $13 }' sample.txt)
#Error=$(awk 'FNR==1 { print $8 }' sample.txt)
# After extracting the adsorption data and error value, printing it out 
#echo -n ",$Uptake,$Error" >> ../../../../../${Up_file[$k]}.csv
echo "$density"
#rm sample.txt
