#!/bin/bash

## This script would submit jobs for creating GNUplot images 

#Creating array for corresponding Z axis fraction and its position 
TYPE=(Inner_positive)
TYPES=(Inner)
Z=(0 1 2 3 4 5 6 7 8 9 10 11 12 13 14)
Z_name=(0.00 0.22 0.44 0.66 0.88 1.10 1.32 1.54 1.76 1.98 2.20 2.42 2.64 2.86 3.08)

for ((i=0;i<=15;i++))
do
# creating a folder named off of Z-axis position
if [ -d ${Z_name[$i]} ]; then
rm -r ${Z_name[$i]} 
fi
mkdir ${Z_name[$i]}
cd ${Z_name[$i]}
#copying all the relevant files for creating the surface plot
cp ../2D-surface.gnuplot ../F_${TYPES}Z${Z[$i]}.csv ../raspa-sh .
#changing the address in the condor submission scripts
sed -i 's/TYPE/'${TYPE}'/' raspa-sh
#changing the z axis fraction and position in the gnuplot script
sed -i 's/XYZ/'${Z[$i]}'/' 2D-surface.gnuplot
sed -i 's/POS/'${Z_name[$i]}'/' 2D-surface.gnuplot
#submitting the final job
qsub raspa-sh
#coming out to the main directory
cd ..
done
